# Don't edit Configs-Version manually!
Configs-Version: 5

Options:
  # Locale language. Will search for specified .yml file in ProtocolStringReplacer/Locales.
  # This setting also involve some internal operations, so it's recommended to
  # follow the specification: language(Lower case)-location(Upper case)
  Locale: en-US

  # Set the host of update server, if you need.
  Git-Raw-Host: 'raw.githubusercontent.com'

  # How many times will PSR print stacktrace caused by ProtocolLib ? Set 0 to diable it always.
  ProtocolLib-Side-Stack-Print-Count: 3

  Features:
    # Console related options.
    Console:
      # Show loaded replacer configs in console.
      Print-Replacer-Config-When-Loaded: true

    # Custom plugin placeholder format. It is recommended to use the format that players can't think of,
    # so they cannot access some information that they should not be obtained.
    # By default, you can use the format with ｛player_name｝(Chinese character) to use the placeholder.
    # You may need to edit them for convenient usage.
    Placeholder:
      # The prefix of a placeholder. Only one character allowed.
      Placeholder-Head: ｛
      # The suffix of a placeholder. Only one character allowed.
      Placeholder-Tail: ｝
      # Whether PSR should parse placeholders for console or not.
      Parse-For-Console: true

    # Replaced ItemStack cache related options.
    ItemMetaCache:
      # Seconds to execute the task of purging the cache.
      Purge-Task-Interval: 600
      # Only Purge the cache entries that have not been accessed in these seconds.
      Purge-Access-Interval: 300

    # Packet listener related options.
    Packet-Listener:
      # Specify the listener priority of ProtocolStringReplacer.
      # If PSR conflicts with other plugins also using ProtocolLib, please change this value.
      Listener-Priority: HIGHEST
      # Should PSR forcibly edit the data in packets that are not allowed to be written?
      # It's ok to set it to true.
      Force-Replace: false

    # Chat packets options
    Chat-Packet:
      # Only for 1.19. When enabled, PSR will convert all PLAYER_CHAT packets to SYSTEM_CHAT,
      # to solve the problem that the chat messages from player don't display
      # if server/client enabled "Only Show Secure Chat".
      # NOTE: This affects detection of player chat on clients. E.g, you will not able to report other players via chat.
      Convert-Player-Chat: true
